name: Agent Move & Build

on:
  workflow_dispatch:

jobs:
  agent:
    runs-on: ubuntu-latest

    env:
      AGENTTEST: ${{ secrets.AGENTTEST }}

    steps:
      # Step 1: checkout repo
      - uses: actions/checkout@v4

      # Step 2: set up Node 18 and pnpm (avoids URLSearchParams bug on Node 20)
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      # Step 3: Lint project
      - name: Lint project
        run: pnpm -w run lint

      # Step 4: Build (if script exists)
      - name: Build project
        run: pnpm build || true

      # Step 5: اجرای اسکریپت Agent
      - name: Run agent script
        run: |
          export GITHUB_TOKEN="$AGENTTEST"
          bash agent-script.sh     # یا مسیری که اسکریپت Agent تو قرار دارد
