name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'


      - name: Install dependencies
        run: npm ci

      - name: Install docs dependencies
        working-directory: docs
        run: npm ci --ignore-engines

      - name: Install decision tree dependencies
        working-directory: decision-tree-app
        run: npm ci --legacy-peer-deps

      - name: Build decision tree widget
        working-directory: decision-tree-app
        run: |
          npm run build

      - name: Build docs site
        working-directory: docs
        run: npm run build

      - name: Copy widget to dist
        run: |
          mkdir -p docs/dist/widget
          cp -r decision-tree-app/dist/* docs/dist/widget/


      - name: Run tests
        run: |
          npx http-server docs -p 4173 &
          npx playwright install --with-deps
          npm test
          kill $(jobs -p)

      # build steps are performed before tests so the site exists

      - name: Deploy to gh-pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
          enable_jekyll: false
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          publish_branch: gh-pages

