name: CI — Lint & Test (soft, no deploy)

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          check-latest: true
      - name: Setup pnpm (no explicit version)
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Get pnpm store path
        id: pnpm-store
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install workspaces (frozen→fallback)
        run: |
          pnpm -w install --frozen-lockfile || pnpm -w install
          pnpm -C decision-tree-app install --frozen-lockfile || pnpm -C decision-tree-app install || true
          pnpm -C docs install --frozen-lockfile || pnpm -C docs install || true
      - name: Lint (soft)
        run: pnpm -r --if-present lint || true
        continue-on-error: true
      - name: Build (if present)
        run: |
          pnpm -C decision-tree-app run build-widget || true
          pnpm -C docs run build || true
      - name: Test (soft)
        run: pnpm -r --if-present test || true
        continue-on-error: true
