name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Build decision tree widget
        working-directory: decision-tree-app
        run: |
          npm ci --legacy-peer-deps
          npm run build
          rm -rf ../docs/widget/*
          mkdir -p ../docs/widget
          cp -r dist/* ../docs/widget/

      - name: Build docs site
        working-directory: docs
        run: |
          npm ci
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/dist
          publish_branch: gh-pages

