name: CI/CD – Build, Test & Deploy

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies (monorepo)
        run: pnpm install --frozen-lockfile

      - name: Lint all packages
        run: |
          pnpm --filter ./docs lint || true
          pnpm --filter ./decision-tree-app lint || true

      - name: Unit tests for docs
        run: pnpm --filter ./docs test || echo "No tests in docs"
      - name: Unit tests for decision-tree-app
        run: pnpm --filter ./decision-tree-app test || echo "No tests in decision-tree-app"

      - name: Build docs
        run: pnpm --filter ./docs build
      - name: Build decision-tree-app
        run: pnpm --filter ./decision-tree-app build

      - name: Playwright install and E2E tests
        run: |
          pnpm exec playwright install
          pnpm exec playwright test

      - name: Upload build artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/deploy-pages@v4
