name: Deploy Parsana Energy to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Use pnpm/action-setup@v4 to avoid Node 20 URLSearchParams issues
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Build decision-tree widget
        run: pnpm --filter decision-tree-app run build-widget

      - name: Build docs site
        run: pnpm --filter docs run build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
