name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths: ["docs/**","decision-tree-app/**"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Build decision-tree widget
        continue-on-error: true
        working-directory: decision-tree-app
        run: |
          npm ci --legacy-peer-deps
          npm run build-widget
      - name: Build landing
        working-directory: docs
        run: |
          npm ci --legacy-peer-deps
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist
  deploy:
    if: ${{ always() }}
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          cname: parsanaenergy.ir

